CREATE TABLE "ventas_original" (
    "id_venta" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad" TEXT,
    "cantidad_unidades" TEXT,
    "precio_unitario" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "ingreso_venta" TEXT,
    "observacion" TEXT,
    "locales_nombre" TEXT,
    "locales_distrito" TEXT,
    "locales_zona" TEXT,
    "productos_nombre" TEXT,
    "productos_categoria" TEXT,
    "productos_precio_unitario" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
