CREATE TABLE "pedidos_original" (
    "id_pedido" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_platos" TEXT,
    "tiempo_preparacion_min" TEXT,
    "precio_plato" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "total_pedido" TEXT,
    "observacion" TEXT,
    "locales_nombre" TEXT,
    "locales_distrito" TEXT,
    "locales_zona" TEXT,
    "platos_nombre" TEXT,
    "platos_categoria" TEXT,
    "platos_precio_plato" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
