CREATE TABLE "asistencias_pagos_original" (
    "id_registro" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "clases_tomadas" TEXT,
    "asistencias_mes" TEXT,
    "tarifa_plan" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "pago_mensual" TEXT,
    "observacion" TEXT,
    "sedes_nombre" TEXT,
    "sedes_distrito" TEXT,
    "sedes_zona" TEXT,
    "planes_nombre" TEXT,
    "planes_categoria" TEXT,
    "planes_tarifa_plan" REAL,
    "socios_nombre" TEXT,
    "socios_distrito" TEXT,
    "socios_segmento" TEXT,
    "socios_fecha_registro" TEXT
);
