CREATE TABLE "consumos_original" (
    "id_consumo" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "electrodomesticos" TEXT,
    "numero_habitantes" TEXT,
    "tarifa_base" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "consumo_kwh" TEXT,
    "observacion" TEXT,
    "distritos_nombre" TEXT,
    "distritos_distrito" TEXT,
    "distritos_zona" TEXT,
    "tarifas_nombre" TEXT,
    "tarifas_categoria" TEXT,
    "tarifas_tarifa_base" REAL,
    "hogares_nombre" TEXT,
    "hogares_distrito" TEXT,
    "hogares_segmento" TEXT,
    "hogares_fecha_registro" TEXT
);
