CREATE TABLE "envios_original" (
    "id_envio" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_paquetes" TEXT,
    "peso_paquete_kg" TEXT,
    "tarifa_base" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "costo_envio" TEXT,
    "observacion" TEXT,
    "sedes_nombre" TEXT,
    "sedes_distrito" TEXT,
    "sedes_zona" TEXT,
    "tipos_envio_nombre" TEXT,
    "tipos_envio_categoria" TEXT,
    "tipos_envio_tarifa_base" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
