CREATE TABLE "ordenes_original" (
    "id_orden" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_repuestos" TEXT,
    "horas_trabajo" TEXT,
    "tarifa_base" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "costo_reparacion" TEXT,
    "observacion" TEXT,
    "sedes_nombre" TEXT,
    "sedes_distrito" TEXT,
    "sedes_zona" TEXT,
    "servicios_nombre" TEXT,
    "servicios_categoria" TEXT,
    "servicios_tarifa_base" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
