CREATE TABLE "reservas_original" (
    "id_reserva" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_habitaciones" TEXT,
    "noches_estadia" TEXT,
    "tarifa_noche" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "monto_reserva" TEXT,
    "observacion" TEXT,
    "hoteles_nombre" TEXT,
    "hoteles_distrito" TEXT,
    "hoteles_zona" TEXT,
    "habitaciones_nombre" TEXT,
    "habitaciones_categoria" TEXT,
    "habitaciones_tarifa_noche" REAL,
    "huespedes_nombre" TEXT,
    "huespedes_distrito" TEXT,
    "huespedes_segmento" TEXT,
    "huespedes_fecha_registro" TEXT
);
