CREATE TABLE "ventas_original" (
    "id_venta" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_unidades" TEXT,
    "precio_venta_unitario" TEXT,
    "costo_unitario" TEXT,
    "descuento_pct" TEXT,
    "stock_inicial" TEXT,
    "stock_final" TEXT,
    "merma_unidades" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "monto_venta_soles" TEXT,
    "margen_venta_soles" TEXT,
    "observacion" TEXT,
    "tiendas_nombre" TEXT,
    "tiendas_distrito" TEXT,
    "tiendas_zona" TEXT,
    "tiendas_tipo_local" TEXT,
    "productos_nombre" TEXT,
    "productos_categoria" TEXT,
    "productos_proveedor" TEXT,
    "productos_costo_unitario" REAL,
    "productos_precio_lista" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
