CREATE TABLE "paradas_original" (
    "id_parada" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "tiempo_operacion_h" TEXT,
    "unidades_producidas" TEXT,
    "defectos_unidades" TEXT,
    "temperatura_promedio_c" TEXT,
    "velocidad_real_u_h" TEXT,
    "causa_parada" TEXT,
    "criticidad" TEXT,
    "duracion_parada_min" TEXT,
    "costo_parada_soles" TEXT,
    "observacion" TEXT,
    "turnos_nombre" TEXT,
    "turnos_supervisor" TEXT,
    "turnos_hora_inicio" TEXT,
    "turnos_hora_fin" TEXT,
    "procesos_nombre" TEXT,
    "procesos_familia" TEXT,
    "procesos_temperatura_objetivo_c" REAL,
    "procesos_velocidad_objetivo_u_h" REAL,
    "maquinas_nombre" TEXT,
    "maquinas_linea" TEXT,
    "maquinas_tipo_maquina" TEXT,
    "maquinas_antiguedad_anios" REAL
);
