CREATE TABLE "entregas_original" (
    "id_entrega" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_items" TEXT,
    "distancia_km" TEXT,
    "costo_pedido" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "tiempo_entrega_min" TEXT,
    "observacion" TEXT,
    "zonas_nombre" TEXT,
    "zonas_distrito" TEXT,
    "zonas_zona" TEXT,
    "restaurantes_nombre" TEXT,
    "restaurantes_categoria" TEXT,
    "restaurantes_costo_pedido" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
