CREATE TABLE "ventas_original" (
    "id_venta" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad" TEXT,
    "cantidad_medicamentos" TEXT,
    "precio_unitario" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "monto_boleta" TEXT,
    "observacion" TEXT,
    "sucursales_nombre" TEXT,
    "sucursales_distrito" TEXT,
    "sucursales_zona" TEXT,
    "medicamentos_nombre" TEXT,
    "medicamentos_categoria" TEXT,
    "medicamentos_precio_unitario" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
