CREATE TABLE "atenciones_original" (
    "id_atencion" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_servicios" TEXT,
    "duracion_consulta_min" TEXT,
    "tarifa_base" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "costo_atencion" TEXT,
    "observacion" TEXT,
    "sedes_nombre" TEXT,
    "sedes_distrito" TEXT,
    "sedes_zona" TEXT,
    "servicios_nombre" TEXT,
    "servicios_categoria" TEXT,
    "servicios_tarifa_base" REAL,
    "pacientes_nombre" TEXT,
    "pacientes_distrito" TEXT,
    "pacientes_segmento" TEXT,
    "pacientes_fecha_registro" TEXT
);
