CREATE TABLE "produccion_original" (
    "id_produccion" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_jornales" TEXT,
    "hectareas" TEXT,
    "costo_insumo" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "rendimiento_kg" TEXT,
    "observacion" TEXT,
    "zonas_nombre" TEXT,
    "zonas_distrito" TEXT,
    "zonas_zona" TEXT,
    "cultivos_nombre" TEXT,
    "cultivos_categoria" TEXT,
    "cultivos_costo_insumo" REAL,
    "parcelas_nombre" TEXT,
    "parcelas_distrito" TEXT,
    "parcelas_segmento" TEXT,
    "parcelas_fecha_registro" TEXT
);
