CREATE TABLE "atenciones_original" (
    "id_atencion" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad_servicios" TEXT,
    "peso_mascota_kg" TEXT,
    "tarifa_base" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "costo_servicio" TEXT,
    "observacion" TEXT,
    "sedes_nombre" TEXT,
    "sedes_distrito" TEXT,
    "sedes_zona" TEXT,
    "servicios_nombre" TEXT,
    "servicios_categoria" TEXT,
    "servicios_tarifa_base" REAL,
    "mascotas_nombre" TEXT,
    "mascotas_distrito" TEXT,
    "mascotas_segmento" TEXT,
    "mascotas_fecha_registro" TEXT
);
