CREATE TABLE "ventas_original" (
    "id_venta" INTEGER PRIMARY KEY,
    "fecha_operacion" TEXT,
    "cantidad" TEXT,
    "cantidad_articulos" TEXT,
    "precio_unitario" TEXT,
    "descuento_pct" TEXT,
    "canal" TEXT,
    "metodo_pago" TEXT,
    "calificacion" TEXT,
    "monto_compra" TEXT,
    "observacion" TEXT,
    "tiendas_nombre" TEXT,
    "tiendas_distrito" TEXT,
    "tiendas_zona" TEXT,
    "articulos_nombre" TEXT,
    "articulos_categoria" TEXT,
    "articulos_precio_unitario" REAL,
    "clientes_nombre" TEXT,
    "clientes_distrito" TEXT,
    "clientes_segmento" TEXT,
    "clientes_fecha_registro" TEXT
);
